#
# linsys2-makepkg - build MSYS2 mingw-w64 packages on Linux (experimental)
#
# Copyright (C) 2026 Zhou Qiankang <wszqkzqk@qq.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
import fcntl
import functools
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from linsys2 import __version__
from linsys2.common import (
    BIN_DIR,
    CONFIG_DIR,
    DEFAULT_ENV,
    ENVIRONMENTS,
    LIBALPM_DIR,
    LIBMAKEPKG_DIR,
    MAKEPKG_BIN,
    MAKEPKG_CONF,
    PACMAN_CONF_BIN,
    disable_winemenubuilder,
    error,
    get_bin_dir,
    get_env_dir,
    get_wineprefix,
    info,
    resolve_wineprefix,
    warn,
)

WRAPPER_MARKER = "# generated by linsys2-makepkg"

CYGPATH_SHIM_FILE = Path(__file__).resolve().parent / "shims" / "cygpath"
UNAME_SHIM_FILE = Path(__file__).resolve().parent / "shims" / "uname"

SHIM_NAMES = ("pacman", "pacman-conf", "cygpath", "uname", "arch")


def get_build_bin_dir(env_name):
    return get_env_dir(env_name) / "build-bin"


def winepath_of_bin_dir(env_name):
    """Windows view of the environment's bin directory (Z: maps to /)."""
    return "Z:" + str(get_bin_dir(env_name)).replace("/", "\\")


def _windows_path_of(linux_path, wineprefix):
    """linux_path as the prefix's Windows programs see it (via winepath)."""
    env = os.environ.copy()
    env["WINEPREFIX"] = str(wineprefix)
    env["WINEDEBUG"] = "-all"
    env["LC_ALL"] = "C.UTF-8"
    try:
        return subprocess.run(["winepath", "-w", str(linux_path)], env=env,
                              capture_output=True, encoding="utf-8",
                              check=True, timeout=30).stdout.strip()
    except (OSError, UnicodeDecodeError, subprocess.CalledProcessError,
            subprocess.TimeoutExpired):
        return "Z:" + str(linux_path).replace("/", "\\")


def _write_if_changed(path, content, mode=0o755):
    if path.exists() and path.read_text(errors="replace") == content:
        return
    path.write_text(content)
    path.chmod(mode)


def ensure_wineprefix(wineprefix):
    if not (wineprefix / "dosdevices").is_dir():
        info(f"Initializing Wine prefix: {wineprefix}")
        wineprefix.mkdir(parents=True, exist_ok=True)
        env = os.environ.copy()
        env["WINEPREFIX"] = str(wineprefix)
        disable_winemenubuilder(env)
        env["WINEDEBUG"] = "-all"
        result = subprocess.run(["wineboot", "--init"], env=env, check=False)
        if result.returncode != 0:
            warn("wineboot failed; prefix may be incomplete")


def ensure_build_bin(env_name, wineprefix=None):
    """Generate the build shim directory (exclusively ours): pacman/
    pacman-conf/cygpath/uname/arch shims and a wrapper script for every
    foo.exe and .bat/.cmd tool in the environment's bin dir, so shell
    lookups like `gcc` resolve without writing into the package-managed
    bin dir.

    Wrappers must invoke the real .exe path: Wine derives the module path
    (DLL search, GCC specs, CMake modules) from it. A symlink here would
    report this directory as the module path and break self-location.
    """
    build_bin = get_build_bin_dir(env_name)
    build_bin.mkdir(parents=True, exist_ok=True)

    wineprefix = wineprefix or get_wineprefix(env_name)
    bin_dir = get_bin_dir(env_name)

    exports = (
        f"export WINEPREFIX={shlex.quote(str(wineprefix))}\n"
        f"export WINEDEBUG=-all\n"
    )

    targets = set(SHIM_NAMES)
    if bin_dir.is_dir():
        for entry in sorted(bin_dir.iterdir()):
            name = entry.name
            lower = name.lower()
            if lower.endswith(".exe"):
                wrapper = name[:-4]
                invoke = f"exec wine {shlex.quote(str(entry))} \"$@\"\n"
            elif lower.endswith((".bat", ".cmd")):
                # Bare names resolve to .exe on MSYS2; .bat/.cmd stay explicit.
                wrapper = name
                win_path = _windows_path_of(entry, wineprefix)
                invoke = f"exec wine cmd /c {shlex.quote(win_path)} \"$@\"\n"
            else:
                continue
            if not wrapper or wrapper in targets:
                continue
            targets.add(wrapper)
            _write_if_changed(
                build_bin / wrapper,
                f"#!/bin/sh\n{WRAPPER_MARKER}\n{exports}{invoke}",
            )

    for stale in list(build_bin.iterdir()):
        if stale.name in targets or not stale.is_file():
            continue
        try:
            if WRAPPER_MARKER in stale.read_text():
                stale.unlink()
        except (OSError, UnicodeDecodeError):
            pass

    env_conf = CONFIG_DIR / f"{env_name}.conf"
    _write_if_changed(
        build_bin / "pacman",
        f"#!/bin/sh\n{WRAPPER_MARKER}\n"
        f"exec {shlex.quote(sys.executable)} "
        f"{shlex.quote(str(BIN_DIR / 'linsys2-pacman'))} --env {env_name} \"$@\"\n",
    )
    _write_if_changed(
        build_bin / "pacman-conf",
        f"#!/bin/sh\n{WRAPPER_MARKER}\n"
        f"exec {shlex.quote(str(PACMAN_CONF_BIN))} --config {shlex.quote(str(env_conf))} \"$@\"\n",
    )
    # Absolute interpreter, like the installed entry points: with the
    # environment's Windows python3 wrapper first on PATH, /usr/bin/env
    # python3 would run these shims under Windows Python (CRLF output).
    cygpath_shim = CYGPATH_SHIM_FILE.read_text().replace(
        "#!/usr/bin/env python3", f"#!{sys.executable}", 1)
    _write_if_changed(build_bin / "cygpath", cygpath_shim)

    machine = ENVIRONMENTS[env_name]["chost"].partition("-")[0]
    uname_shim = (UNAME_SHIM_FILE.read_text()
                  .replace("#!/usr/bin/env python3", f"#!{sys.executable}", 1)
                  .replace("@machine@", machine)
                  .replace("@wineprefix@", repr(str(wineprefix))))
    _write_if_changed(build_bin / "uname", uname_shim)
    _write_if_changed(build_bin / "arch", uname_shim)


def check_bwrap(env_name):
    if shutil.which("bwrap"):
        return True
    prefix = ENVIRONMENTS[env_name]["install_prefix"]
    error("bubblewrap (bwrap) not found.")
    error("linsys2-makepkg uses it to give the build a private filesystem")
    error(f"view with the environment prefix at {prefix}. Install bubblewrap.")
    return False


def check_wine():
    if shutil.which("wineboot"):
        return True
    error("wine not found.")
    error("linsys2-makepkg needs it to initialize the build's Wine prefix.")
    error("Install wine.")
    return False


@functools.lru_cache(maxsize=1)
def _can_mount_fresh_proc():
    """Containers masking /proc submounts (systemd-nspawn, ...) make the
    kernel reject a fresh procfs mount with EPERM; then bind the existing
    /proc instead."""
    try:
        return subprocess.run(
            ["bwrap", "--unshare-user", "--unshare-pid", "--die-with-parent",
             "--dev-bind", "/", "/", "--proc", "/proc", "true"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            check=False).returncode == 0
    except OSError:
        return False


def build_bwrap_argv(env_name, makepkg_cmd):
    """Assemble the bubblewrap command line running makepkg_cmd in a
    private mount namespace where the environment prefix is mounted at
    its MSYS2 location (/ucrt64, ...), so both native build scripts with
    the prefix baked in and Wine processes (Z: -> /) resolve it.
    """
    env_cfg = ENVIRONMENTS[env_name]
    install_prefix = env_cfg["install_prefix"]
    env_prefix = get_env_dir(env_name) / install_prefix.lstrip("/")

    argv = ["bwrap", "--unshare-user", "--unshare-pid", "--die-with-parent"]
    fresh_proc = _can_mount_fresh_proc()
    for top in sorted(os.listdir("/")):
        src = "/" + top
        if not os.path.isdir(src):
            continue
        if top == install_prefix.lstrip("/"):
            continue  # the environment prefix is mounted there below
        if os.path.islink(src):
            argv += ["--symlink", os.readlink(src), src]
        elif top == "proc":
            argv += ["--proc", "/proc"] if fresh_proc else ["--bind", src, src]
        elif top == "dev":
            argv += ["--dev", "/dev", "--tmpfs", "/dev/shm"]
        elif top in ("sys", "boot", "efi"):
            argv += ["--ro-bind", src, src]
        else:
            argv += ["--bind", src, src]
    argv += ["--dir", install_prefix,
             "--bind", str(env_prefix), install_prefix]
    argv += ["--", "bash", "-c",
             # Restart wineserver inside this namespace so its filesystem
             # view matches, and tear it down on exit.
             'wineserver -k 2>/dev/null; "$@"; rc=$?; '
             'wineserver -k 2>/dev/null; exit $rc',
             "bash"] + makepkg_cmd
    return argv


def acquire_env_lock(env_name):
    """Take the per-environment build lock; concurrent builds share the
    WINEPREFIX and would kill each other's wineserver on entry and exit."""
    env_dir = get_env_dir(env_name)
    env_dir.mkdir(parents=True, exist_ok=True)
    fd = os.open(env_dir / ".makepkg.lock", os.O_CREAT | os.O_RDWR, 0o644)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        os.close(fd)
        return None
    return fd


def pacman_auth(cmd_argv):
    """PACMAN_AUTH hook: run makepkg's pacman command, refreshing the
    build wrappers after a successful transaction."""
    if not cmd_argv:
        error("pacman-auth: no command given")
        return 1
    try:
        rc = subprocess.call(cmd_argv)
    except OSError as e:
        error(f"pacman-auth: {e}")
        return 127
    except KeyboardInterrupt:
        return 130
    # shell convention: killed by signal N -> 128+N
    if rc < 0:
        rc = 128 - rc
    if rc == 0:
        env_name = os.environ.get("LINSYS2_ENV")
        if env_name in ENVIRONMENTS:
            wp = os.environ.get("WINEPREFIX")
            try:
                ensure_build_bin(env_name, Path(wp) if wp else None)
            except Exception as e:
                warn(f"failed to refresh build wrappers: {e}")
        else:
            warn("pacman-auth: LINSYS2_ENV unset, skipping wrapper refresh")
    return rc


def run_makepkg(env_name, makepkg_args, wineprefix_arg=None):
    env_cfg = ENVIRONMENTS[env_name]
    env_conf = CONFIG_DIR / f"{env_name}.conf"

    if not MAKEPKG_BIN.exists():
        error(f"makepkg not found: {MAKEPKG_BIN}")
        return 1
    if not MAKEPKG_CONF.exists():
        error(f"makepkg config not found: {MAKEPKG_CONF}")
        return 1
    if not env_conf.exists():
        error(f"Environment not initialized: {env_name}")
        error(f"Run: linsys2-pacman init --env {env_name}")
        return 1
    if not check_bwrap(env_name):
        return 1
    if not check_wine():
        return 1

    lock_fd = acquire_env_lock(env_name)
    if lock_fd is None:
        error(f"environment '{env_name}' is in use by another linsys2-makepkg")
        return 1

    try:
        wineprefix = resolve_wineprefix(env_name, wineprefix_arg)
        ensure_wineprefix(wineprefix)
        ensure_build_bin(env_name, wineprefix)

        env = os.environ.copy()
        env["MSYSTEM"] = env_cfg["msystem"]
        env["CHERE_INVOKING"] = "1"
        env["MSYS2_PACMAN_LINUX"] = "1"
        env["LINSYS2_ENV"] = env_name
        env["WINEPREFIX"] = str(wineprefix)
        env["WINEPATH"] = winepath_of_bin_dir(env_name)
        env["WINEDEBUG"] = "-all"
        env["PANGOCAIRO_BACKEND"] = "fontconfig"
        env["MAKEPKG_LIBRARY"] = str(LIBMAKEPKG_DIR)
        # gcc -print-prog-name=ld yields a Z:/... path that native bash cannot
        # execute; a bare name resolved via PATH makes libtool detect GNU ld
        # instead of falling back to its MSVC branch.
        env.setdefault("LD", "ld")
        # libtool validates gcc's library search paths with test -d, which fails
        # for the Z:/... forms; preseed the autoconf cache with the real
        # (in-namespace) prefix paths instead.
        prefix = env_cfg["install_prefix"]
        env.setdefault(
            "lt_cv_sys_lib_search_path_spec",
            f"{prefix}/lib {prefix}/{env_cfg['chost']}/lib /usr/lib /lib",
        )
        # depfiles would contain Z:\... paths that native GNU make (built
        # without HAVE_DOS_PATHS) cannot parse; one-shot package builds don't
        # need header dependency tracking.
        env.setdefault("am_cv_CC_dependencies_compiler_type", "none")
        env.setdefault("am_cv_CXX_dependencies_compiler_type", "none")
        if LIBALPM_DIR.exists():
            old = env.get("LD_LIBRARY_PATH")
            env["LD_LIBRARY_PATH"] = str(LIBALPM_DIR) + (":" + old if old else "")
        env["PATH"] = ":".join([str(get_build_bin_dir(env_name)),
                                str(get_bin_dir(env_name)),
                                env.get("PATH", "")])

        cmd = [str(MAKEPKG_BIN), "--config", str(MAKEPKG_CONF)] + makepkg_args
        try:
            rc = subprocess.run(build_bwrap_argv(env_name, cmd), env=env).returncode
        except KeyboardInterrupt:
            return 130
        # shell convention: killed by signal N -> 128+N
        return 128 - rc if rc < 0 else rc
    finally:
        os.close(lock_fd)


def main():
    argv = sys.argv[1:]

    if argv and argv[0] in ("-V", "--version"):
        print(f"linsys2-makepkg {__version__}")
        return 0

    if argv[:1] == ["--pacman-auth"]:
        return pacman_auth(argv[1:])

    env_choices = list(ENVIRONMENTS.keys())

    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--env", default=None, choices=env_choices,
                     help=f"target environment (default: {DEFAULT_ENV})")
    pre.add_argument("--prefix", default=None, metavar="WINEPREFIX",
                     help="build inside this existing Wine prefix "
                          "(default: the environment's managed prefix)")
    pre.add_argument("-h", "--help", action="store_true",
                     help="show this help message and exit")
    pre_args, makepkg_args = pre.parse_known_args(argv)

    if pre_args.help:
        pre.print_help()
        print(f"""
Build MSYS2 mingw-w64 packages on Linux (experimental). All remaining
arguments are passed to makepkg. Examples:
  linsys2-makepkg -sLf              # build, installing mingw deps
  linsys2-makepkg --env clang64 -s  # build for clang64
  linsys2-makepkg --verifysource    # only verify sources

Environments: {', '.join(env_choices)} (default: {DEFAULT_ENV})
The MINGW_ARCH environment variable may hold a space-separated list of
environments to build for, like MSYS2's makepkg-mingw.
""")
        return 0

    mingw_arch = os.environ.get("MINGW_ARCH", "").split()
    if mingw_arch:
        envs = []
        for e in mingw_arch:
            e = e.lower()
            if e not in ENVIRONMENTS:
                error(f"MINGW_ARCH: '{e}' unknown, possible values: {env_choices}")
                return 1
            envs.append(e)
    else:
        envs = [pre_args.env or DEFAULT_ENV]

    ret = 0
    for env_name in envs:
        if len(envs) > 1:
            info(f"Building for {env_name}...")
        rc = run_makepkg(env_name, makepkg_args, pre_args.prefix)
        if rc != 0:
            ret = rc
            break

    return ret
